// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF-guN1jzVgujkKHty6Snozp-A2iNax3w',
    appId: '1:883743026601:web:f2f794d198912e450428b8',
    messagingSenderId: '883743026601',
    projectId: 'messageapp-e4756',
    authDomain: 'messageapp-e4756.firebaseapp.com',
    storageBucket: 'messageapp-e4756.firebasestorage.app',
    measurementId: 'G-S1RSG0D22H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4b5QoJlVIlSMEilR3YZ1dLfPJJMoD2OM',
    appId: '1:883743026601:android:a8a001a2ccbbb0b80428b8',
    messagingSenderId: '883743026601',
    projectId: 'messageapp-e4756',
    storageBucket: 'messageapp-e4756.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0V6fVcEaqezzXRWDEIpX6pWmJB0h99DY',
    appId: '1:883743026601:ios:61adebc99c56a7740428b8',
    messagingSenderId: '883743026601',
    projectId: 'messageapp-e4756',
    storageBucket: 'messageapp-e4756.firebasestorage.app',
    iosBundleId: 'com.example.msgApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0V6fVcEaqezzXRWDEIpX6pWmJB0h99DY',
    appId: '1:883743026601:ios:61adebc99c56a7740428b8',
    messagingSenderId: '883743026601',
    projectId: 'messageapp-e4756',
    storageBucket: 'messageapp-e4756.firebasestorage.app',
    iosBundleId: 'com.example.msgApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF-guN1jzVgujkKHty6Snozp-A2iNax3w',
    appId: '1:883743026601:web:fbbc8731b465f8d20428b8',
    messagingSenderId: '883743026601',
    projectId: 'messageapp-e4756',
    authDomain: 'messageapp-e4756.firebaseapp.com',
    storageBucket: 'messageapp-e4756.firebasestorage.app',
    measurementId: 'G-QDXV95Q50N',
  );
}
